services:
  frontend:
    build:
      context: ./FrontEnd  
      dockerfile: Dockerfile  
    image: auth-app-fe-image  
    container_name: AUTH-APP-FE  
    ports:
      - "5173:80"  # Map host port 5173 to container port 80 (Nginx)
    restart: unless-stopped

  backend:
    build:
      context: ./BackEnd  
      dockerfile: Dockerfile  
    image: auth-app-be-image  
    container_name: AUTH-APP-BE  
    ports:
      - "3002:3002"  
    restart: unless-stopped
    environment:  
      - NODE_ENV=production